# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-09 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginformapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='password1',
            new_name='passwordd',
        ),
    ]
